import { MigrationInterface, QueryRunner } from 'typeorm';

export class asd1693358484433 implements MigrationInterface {
  name = 'asd1693358484433';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "Clasroom" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying NOT NULL, "deletedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_4b18d5e7c02d0b698b3f8d15963" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "ImageType" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying(1024) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_04ac508e649bcec252a35379351" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "Schedule" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "startDate" TIMESTAMP WITH TIME ZONE NOT NULL, "endDate" TIMESTAMP WITH TIME ZONE NOT NULL, "startHour" TIME NOT NULL, "endHour" TIME NOT NULL, "scheduleDays" character varying NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_1e0db675cb5a22276ffd69b1a5a" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "Sector" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying(1024) NOT NULL, "topic" character varying(1024) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_4167cf23fa540adbb11cc5b4825" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "User" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying(1024) NOT NULL, "dni" character varying(1024) NOT NULL, "password" character varying(1024) NOT NULL, "deletedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP WITH TIME ZONE NOT NULL, "roleId" integer, CONSTRAINT "PK_9862f679340fb2388436a5ab3e4" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "Image" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying NOT NULL, "deletedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP WITH TIME ZONE NOT NULL, "imageTypeId" integer, "userId" integer, "sectorId" integer, "scheduleId" integer, CONSTRAINT "PK_ddecd6b02f6dd0d3d10a0a74717" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "Screen" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "subscription" character varying(100) NOT NULL, "deletedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP WITH TIME ZONE NOT NULL, "sectorId" integer, CONSTRAINT "PK_bf86825808b3babf300fad57b2f" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "ImageScreen" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "imageId" integer, "screenId" integer, CONSTRAINT "PK_5a8060218c9d3e456efb9781855" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "Subject" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying(1024) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_ea85b796e06e827fbb699842d58" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "Course" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "userId" integer, "sectorId" integer, "scheduleId" integer, "subjectId" integer, "classroomId" integer, CONSTRAINT "PK_2132e2054a5c04b038320b38c11" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "CourseScreen" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "deletedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP WITH TIME ZONE NOT NULL, "courseId" integer, "screenId" integer, CONSTRAINT "PK_3ce824a52e194b0cd3442df1ca9" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `ALTER TABLE "User" ADD CONSTRAINT "FK_0b8c60cc29663fa5b9fb108edd7" FOREIGN KEY ("roleId") REFERENCES "Clasroom"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "Image" ADD CONSTRAINT "FK_1698fb466acc3cc1bae1ac89944" FOREIGN KEY ("imageTypeId") REFERENCES "ImageType"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "Image" ADD CONSTRAINT "FK_7c69fd41f9e07936e1a59698ae1" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "Image" ADD CONSTRAINT "FK_f639db790787a24653af5aed09f" FOREIGN KEY ("sectorId") REFERENCES "Sector"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "Image" ADD CONSTRAINT "FK_be7d28c72b37d7ac5341027d2c1" FOREIGN KEY ("scheduleId") REFERENCES "Schedule"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "Screen" ADD CONSTRAINT "FK_2374181548ba49b8c2e6e3a7ced" FOREIGN KEY ("sectorId") REFERENCES "Sector"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "ImageScreen" ADD CONSTRAINT "FK_f60dfde284aa86c3922d66ff020" FOREIGN KEY ("imageId") REFERENCES "Image"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "ImageScreen" ADD CONSTRAINT "FK_c985c41a45b5d992398f97ed1a0" FOREIGN KEY ("screenId") REFERENCES "Screen"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "Course" ADD CONSTRAINT "FK_2d3ae7fc1f3090a4fa020729769" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "Course" ADD CONSTRAINT "FK_f45b26770933751b6f1fc03a06a" FOREIGN KEY ("sectorId") REFERENCES "Sector"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "Course" ADD CONSTRAINT "FK_88a8486e09bca1b969d4fb1e175" FOREIGN KEY ("scheduleId") REFERENCES "Schedule"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "Course" ADD CONSTRAINT "FK_f1374564cf131d69c62896c77e7" FOREIGN KEY ("subjectId") REFERENCES "Subject"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "Course" ADD CONSTRAINT "FK_ddae32113f4ef42f1d01838e84f" FOREIGN KEY ("classroomId") REFERENCES "Clasroom"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "CourseScreen" ADD CONSTRAINT "FK_a2fb3bd3f4ad5545e6c0924c211" FOREIGN KEY ("courseId") REFERENCES "Course"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "CourseScreen" ADD CONSTRAINT "FK_7adcdb55d8b2a445a50470f11ca" FOREIGN KEY ("screenId") REFERENCES "Screen"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "CourseScreen" DROP CONSTRAINT "FK_7adcdb55d8b2a445a50470f11ca"`,
    );
    await queryRunner.query(
      `ALTER TABLE "CourseScreen" DROP CONSTRAINT "FK_a2fb3bd3f4ad5545e6c0924c211"`,
    );
    await queryRunner.query(
      `ALTER TABLE "Course" DROP CONSTRAINT "FK_ddae32113f4ef42f1d01838e84f"`,
    );
    await queryRunner.query(
      `ALTER TABLE "Course" DROP CONSTRAINT "FK_f1374564cf131d69c62896c77e7"`,
    );
    await queryRunner.query(
      `ALTER TABLE "Course" DROP CONSTRAINT "FK_88a8486e09bca1b969d4fb1e175"`,
    );
    await queryRunner.query(
      `ALTER TABLE "Course" DROP CONSTRAINT "FK_f45b26770933751b6f1fc03a06a"`,
    );
    await queryRunner.query(
      `ALTER TABLE "Course" DROP CONSTRAINT "FK_2d3ae7fc1f3090a4fa020729769"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ImageScreen" DROP CONSTRAINT "FK_c985c41a45b5d992398f97ed1a0"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ImageScreen" DROP CONSTRAINT "FK_f60dfde284aa86c3922d66ff020"`,
    );
    await queryRunner.query(
      `ALTER TABLE "Screen" DROP CONSTRAINT "FK_2374181548ba49b8c2e6e3a7ced"`,
    );
    await queryRunner.query(
      `ALTER TABLE "Image" DROP CONSTRAINT "FK_be7d28c72b37d7ac5341027d2c1"`,
    );
    await queryRunner.query(
      `ALTER TABLE "Image" DROP CONSTRAINT "FK_f639db790787a24653af5aed09f"`,
    );
    await queryRunner.query(
      `ALTER TABLE "Image" DROP CONSTRAINT "FK_7c69fd41f9e07936e1a59698ae1"`,
    );
    await queryRunner.query(
      `ALTER TABLE "Image" DROP CONSTRAINT "FK_1698fb466acc3cc1bae1ac89944"`,
    );
    await queryRunner.query(
      `ALTER TABLE "User" DROP CONSTRAINT "FK_0b8c60cc29663fa5b9fb108edd7"`,
    );
    await queryRunner.query(`DROP TABLE "CourseScreen"`);
    await queryRunner.query(`DROP TABLE "Course"`);
    await queryRunner.query(`DROP TABLE "Subject"`);
    await queryRunner.query(`DROP TABLE "ImageScreen"`);
    await queryRunner.query(`DROP TABLE "Screen"`);
    await queryRunner.query(`DROP TABLE "Image"`);
    await queryRunner.query(`DROP TABLE "User"`);
    await queryRunner.query(`DROP TABLE "Sector"`);
    await queryRunner.query(`DROP TABLE "Schedule"`);
    await queryRunner.query(`DROP TABLE "ImageType"`);
    await queryRunner.query(`DROP TABLE "Clasroom"`);
  }
}
