import { MigrationInterface, QueryRunner } from 'typeorm';

export class updateColumnDelete1693401602018 implements MigrationInterface {
  name = 'updateColumnDelete1693401602018';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "Course" DROP CONSTRAINT "FK_ddae32113f4ef42f1d01838e84f"`,
    );
    await queryRunner.query(
      `CREATE TABLE "Classroom" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_6ff2b3fa3d6fc07411ba4a9cbe0" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `ALTER TABLE "Clasroom" ALTER COLUMN "deletedAt" DROP NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "User" ALTER COLUMN "deleteAt" DROP NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "Schedule" ALTER COLUMN "deletedAt" DROP NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "Screen" ALTER COLUMN "deletedAt" DROP NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "CourseScreen" ALTER COLUMN "deletedAt" DROP NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "Clasroom" ALTER COLUMN "deletedAt" DROP NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "User" ALTER COLUMN "deleteAt" DROP NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "Schedule" ALTER COLUMN "deletedAt" DROP NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "Screen" ALTER COLUMN "deletedAt" DROP NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "CourseScreen" ALTER COLUMN "deletedAt" DROP NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "Course" ADD CONSTRAINT "FK_ddae32113f4ef42f1d01838e84f" FOREIGN KEY ("classroomId") REFERENCES "Classroom"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "Course" DROP CONSTRAINT "FK_ddae32113f4ef42f1d01838e84f"`,
    );
    await queryRunner.query(
      `ALTER TABLE "CourseScreen" ALTER COLUMN "deletedAt" SET NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "Screen" ALTER COLUMN "deletedAt" SET NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "Schedule" ALTER COLUMN "deletedAt" SET NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "User" ALTER COLUMN "deleteAt" SET NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "Clasroom" ALTER COLUMN "deletedAt" SET NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "CourseScreen" ALTER COLUMN "deletedAt" SET NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "Screen" ALTER COLUMN "deletedAt" SET NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "Schedule" ALTER COLUMN "deletedAt" SET NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "User" ALTER COLUMN "deleteAt" SET NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "Clasroom" ALTER COLUMN "deletedAt" SET NOT NULL`,
    );
    await queryRunner.query(`DROP TABLE "Classroom"`);
    await queryRunner.query(
      `ALTER TABLE "Course" ADD CONSTRAINT "FK_ddae32113f4ef42f1d01838e84f" FOREIGN KEY ("classroomId") REFERENCES "Clasroom"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
  }
}
