import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateImage1694632433979 implements MigrationInterface {
  name = 'CreateImage1694632433979';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "Image" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "originalName" character varying NOT NULL, "fileName" character varying NOT NULL, CONSTRAINT "PK_ddecd6b02f6dd0d3d10a0a74717" PRIMARY KEY ("id"))`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "Image"`);
  }
}
