import { MigrationInterface, QueryRunner } from 'typeorm';

export class TablaIntermedia1695776258475 implements MigrationInterface {
  name = 'TablaIntermedia1695776258475';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "AdvertisingSchedule" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "advertisingId" integer, "scheduleId" integer, CONSTRAINT "PK_82aba0d7c15258f3cdeb557c4e3" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `ALTER TABLE "AdvertisingSchedule" ADD CONSTRAINT "FK_b914c0b5ceaa351520e144a29a0" FOREIGN KEY ("advertisingId") REFERENCES "Advertising"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "AdvertisingSchedule" ADD CONSTRAINT "FK_3bd6cfe53121b7ebb29aa79512a" FOREIGN KEY ("scheduleId") REFERENCES "Schedule"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "AdvertisingSchedule" DROP CONSTRAINT "FK_3bd6cfe53121b7ebb29aa79512a"`,
    );
    await queryRunner.query(
      `ALTER TABLE "AdvertisingSchedule" DROP CONSTRAINT "FK_b914c0b5ceaa351520e144a29a0"`,
    );
    await queryRunner.query(`DROP TABLE "AdvertisingSchedule"`);
  }
}
