import { MigrationInterface, QueryRunner } from 'typeorm';

export class Mapa41728659099933 implements MigrationInterface {
  name = 'Mapa41728659099933';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "Map" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "originalName" character varying NOT NULL, "base64Data" text NOT NULL, "name" text NOT NULL, "estaSeleccionado" boolean NOT NULL, "deletedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_7ae6036ece70cc4a6654e0f1f96" PRIMARY KEY ("id"))`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "Map"`);
  }
}
