import { MigrationInterface, QueryRunner } from 'typeorm';

export class Mapa1728394480805 implements MigrationInterface {
  name = 'Mapa1728394480805';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "Map" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "originalName" character varying NOT NULL, "base64Data" text NOT NULL, CONSTRAINT "PK_7ae6036ece70cc4a6654e0f1f96" PRIMARY KEY ("id"))`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "Map"`);
  }
}
